import type { Metadata } from "next";
import { IBM_Plex_Sans , Inter} from "next/font/google";
import "./globals.css";

const IBMPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["500", "600", "700"],
  variable: "--font-ibmplexsans",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: ["500", "600", "700"],
  variable : "--font-inter"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IBMPlexSans.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
